FROM php:8.3-apache



RUN echo '<VirtualHost *:80> \
    DocumentRoot /var/www/html \
    <Directory /var/www/html> \
        Options Indexes FollowSymLinks \
        AllowOverride All \
        Require all granted \
    </Directory> \
</VirtualHost>' > /etc/apache2/sites-available/000-default.conf
